import type { GetServerSideProps, NextPage } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'
import Head from 'next/head'

const Home: NextPage = () => {
  const { t } = useTranslation('common')

  return (
    <div className="container">
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className="header">
        <nav aria-label="Primary">Placeholder navbar</nav>
      </header>

      <main className="main">
        <h1 className="title">
          {t('title')} This is a{' '}
          <a href="https://github.com/navapbc/template-application-nextjs">
            Next.js Template!
          </a>
        </h1>
      </main>

      <footer className="footer">
        <nav aria-label="Secondary">Placeholder Footer</nav>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale || 'en', ['common']))
    }
  }
}

export default Home
