ignore:
  # List of vulnerabilities to ignore for the anchore scan in ./github/actions/image-scan
  # https://github.com/anchore/grype#specifying-matches-to-ignore

  # Example ways to skip or recast CVEs
  # Python CVE for cleo package, poetry requires an older version of cleo that has this CVE
  # - vulnerability: GHSA-2p9h-ccw7-33gf

# This is the full set of supported rule fields:
  # - vulnerability: CVE-2008-4318
  #   fix-state: unknown
  #   package:
  #     name: libcurl
  #     version: 1.5.1
  #     type: npm
  #     location: "/usr/local/lib/node_modules/**"

  # We can make rules to match just by vulnerability ID:
  # - vulnerability: CVE-2017-41432

  # ...or just by a single package field:
  # - package:
  #     type: gem
