# List of vulnerabilities to ignore for the anchore scan
# https://github.com/anchore/grype#specifying-matches-to-ignore
# More info can be found in the docs/infra/vulnerability-management.md file

# Please add whitelists in the following format to make it easier when checking
# Package/module name: URL to vulnerability for checking updates
#  Dependencies: Name of any other packages or modules that are dependent on this version
#                 Link to the dependencies for ease of checking for updates
#  Last checked: Date last checked in scans
# - vulnerability: The-CVE-or-vuln-id # Remove comment at start of line

ignore:
  # Cleo: https://www.cybersecurity-help.cz/vdb/SB2022112226
  #  Dependencies: poetry-core - latest version of poetry is not compatible with
  #                 the latest of cleo, https://pypi.org/project/poetry-core/#history
  #                 The version poetry is able to use has the finding
  #  Last checked: 12-12-2022

  - vulnerability: GHSA-2p9h-ccw7-33gf
  # Certifi: https://cve.report/CVE-2022-23491
  #  Dependencies: None
  #  Last checked: 12-12-2022
  - vulnerability: GHSA-43fp-rhv2-5gv8
