# Specify current major version of docker compose.
# See https://docs.docker.com/compose/compose-file/compose-versioning/
version: '3'

services:
  # Define a service for the Next.js application.
  nextjs:
    build: ./app
    command: ["yarn", "dev"]
    ports:
      # Expose a port to access the application.
      - 3000:3000
      # Expose a port for storybook.
      - 6006:6006
    volumes:
      # Mount the app directory for faster local development.
      - ./app:/srv

