name: Image Vulnerability Scan
description: Run image vulnerability scans
inputs:
  image:
    description: The docker image to scan
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: "image" # Scan type, image or fs
        image-ref: ${{ inputs.image }}
        format: "table" # Can be table, json, sarif, or github
        exit-code: "1" # Exit code to return if any vulnerabilities are found
        ignore-unfixed: true # Ignore unpatched/unfixed vulnerabilities
        vuln-type: "os" # Can be os or library, depending on the type of scan you want to run
        security-checks: "vuln,secret" # Can be any combo of vuln, secret, and config

    - name: Run Anchore vulnerability scan
      uses: anchore/scan-action@v3
      with:
        image: ${{inputs.image}}
        severity-cutoff: "negligible" # Will ignore any findings that are negligible or lower
        output-format: "table" # Can be table, json, or sarif
