import type { NextPage } from 'next'
import Head from 'next/head'
// import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header >
        <nav aria-label="Primary">Placeholder navbar</nav>
      </header>

      <main >
        <h1 >
          Welcome to your{' '}
          <a href="https://github.com/navapbc/template-application-nextjs">
            Next.js Template!
          </a>
        </h1>
      </main>

      <footer >
        <nav aria-label="Secondary">Placeholder Footer</nav>
      </footer>
    </div>
  )
}

export default Home
