import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className={styles.header}>
        <p>Placeholder navbar</p>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to your <a href="https://github.com/navapbc/template-application-nextjs">Next.js Template!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <p>Placeholder footer</p>
      </footer>
    </div>
  )
};

export default Home;