import type { NextPage } from 'next'
import Head from 'next/head'
// this doesn't work because of special uswds-compile stuff
// import styles from '../styles/Home.module.scss'
import styles from '../public/css/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className={styles.header}>
        <nav aria-label="Primary">Placeholder navbar</nav>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to your{' '}
          <a href="https://github.com/navapbc/template-application-nextjs">
            Next.js Template!
          </a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <nav aria-label="Secondary">Placeholder Footer</nav>
      </footer>
    </div>
  )
}

export default Home
