#!/bin/bash
#
# Script to run Playwright tests with a specified app name.
# Requires the APP_NAME environment variable to be set.

# Ensure APP_NAME is provided
if [[ -z "${APP_NAME}" ]]; then
  echo "You must pass in a specific APP_NAME. IE: APP_NAME=app npm run e2e-test" >&2
  exit 1
fi

# Run Playwright tests with the specified app name.
npx playwright test --config "${APP_NAME}/playwright.config.js"
