#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# This script destroys the database layer for an application.
# Do not run this script if you still have the app service layer deployed.
# Run this script in your project's root directory.
#
# Positional parameters:
#   app_name (optional) - the name of the application directory in /infra
#     Defaults to "app".
#   environment (optional) - the name of the environment
#     Defaults to "dev".
# -----------------------------------------------------------------------------
set -euxo pipefail

app_name=${1:-"app"}
environment=${2:-"dev"}
backend_config_file="${environment}.s3.tfbackend"

sed -i.bak 's/deletion_protection = !var.is_temporary/deletion_protection = false/g' infra/modules/database/main.tf
sed -i.bak 's/force_destroy = var.is_temporary/force_destroy = true/g' infra/modules/database/backups.tf

cd "infra/${app_name}/database"

terraform init -reconfigure -backend-config="${backend_config_file}"

terraform apply -auto-approve -target="module.database.aws_backup_vault.backup_vault" -target="module.database.aws_rds_cluster.db" -var="environment_name=${environment}"

terraform destroy -auto-approve -var="environment_name=${environment}"
