#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# This script destroys the database layer for an application.
# Do not run this script if you still have the app service layer deployed.
# Run this script in your project's root directory.
#
# Positional parameters:
#   APP_NAME (optional) - the name of the application directory in /infra
#     Defaults to "app".
#   ENVIRONMENT (optional) - the name of the environment
#     Defaults to "dev".
# -----------------------------------------------------------------------------
set -euxo pipefail

APP_NAME=${1:-"app"}
ENVIRONMENT=${2:-"dev"}
BACKEND_CONFIG_FILE="${ENVIRONMENT}.s3.tfbackend"

sed -i.bak 's/deletion_protection = !var.is_temporary/deletion_protection = false/g' infra/modules/database/main.tf
sed -i.bak 's/force_destroy = var.is_temporary/force_destroy = true/g' infra/modules/database/backups.tf

cd "infra/${APP_NAME}/database"

terraform init -reconfigure -backend-config="${BACKEND_CONFIG_FILE}"

terraform apply -auto-approve -target="module.database.aws_backup_vault.backup_vault" -target="module.database.aws_rds_cluster.db" -var="environment_name=${ENVIRONMENT}"

terraform destroy -auto-approve -var="environment_name=${ENVIRONMENT}"
