#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# This script destroys a network layer.
# Do not run this script if you still have app layers deployed in this network.
# Run this script in your project's root directory.
#
# Positional parameters:
#   network_name (optional) - the name of the network
#     Defaults to "dev".
# -----------------------------------------------------------------------------
set -euxo pipefail

network_name=${1:-"dev"}
backend_config_file="${network_name}.s3.tfbackend"

pushd infra/networks

terraform init -reconfigure -backend-config="${backend_config_file}"

terraform destroy -auto-approve -var="network_name=${network_name}"
