#!/bin/bash
#
# This script installs the template-infra to your project. Run
# this script from your project's root directory.
set -euox pipefail

cur_dir=$(pwd)
script_dir=$(dirname "$0")
template_dir="${script_dir}/.."

echo "Copy files from template-infra"
cd "${template_dir}"
# Note: Keep this list of paths in sync with INCLUDE_PATHS in update-template
cp -r \
  .github \
  bin \
  docs \
  infra \
  Makefile \
  .dockleconfig \
  .gitignore \
  .grype.yml \
  .hadolint.yaml \
  .trivyignore \
  .terraform-version \
  "${cur_dir}"

# Store template version in a file
git rev-parse HEAD > "${cur_dir}/.template-version"

cd -

echo "Remove files relevant only to template development"
# Note: Keep this list of paths in sync with EXCLUDE_OPT in update-template
rm .github/workflows/template-only-*
