environment_name                = "<ENVIRONMENT>"
load_balancer_security_group_id = "<LOAD_BALANCER_SECURITY_GROUP_ID>"
service_security_group_id       = "<SERVICE_SECURITY_GROUP_ID>"
tfstate_bucket                  = "<TF_STATE_BUCKET_NAME>"
tfstate_key                     = "<TF_STATE_KEY>"
region                          = "<REGION>"
