name: Deploy App
# Need to set a default value for when the workflow is triggered from a git push
# which bypasses the default configuration for inputs
run-name: Deploy ${{ inputs.version || 'main' }} to App ${{ inputs.environment || 'dev' }}

on:
  push:
    branches:
      - "main"
    paths:
      - "app/**"
      - "bin/**"
      - "infra/**"
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to be deployed to
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
      version:
        required: true
        default: "main"
        description: Tag or branch or SHA to be deployed

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      app_name: "app"
      environment: ${{ inputs.environment || 'dev' }}
      version: ${{ inputs.version || 'main' }}
