name: CI App PR Environment Update
on:
  workflow_dispatch:
  # !! Uncomment the following lines once you've set up the dev environment and are ready to enable PR environments
  # pull_request:
jobs:
  update:
    name: " " # GitHub UI is noisy when calling reusable workflows, so use whitespace for name to reduce noise
    uses: ./.github/workflows/pr-environment-update.yml
    with:
      app_name: "app"
      environment: "dev"
