name: CI Documentation Checks

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # This is the GitHub Actions-friendly port of the linter used in the Makefile.
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          use-quiet-mode: 'yes'  # errors only.
          config-file: '.github/workflows/markdownlint-config.json'
