name: CI Documentation Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # This is the GitHub Actions-friendly port of the linter used in the Makefile.
      - uses: tcort/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes" # errors only.
          config-file: ".github/workflows/markdownlint-config.json"
          check-modified-files-only: ${{ github.event_name == 'pull_request' && 'yes' || 'no' }}
          base-branch: "main"
