name: CI E2E static checks
run-name: CI E2E static checks

on:
  pull_request:
    paths:
      - "e2e/**"
  push:
    branches:
      - main

jobs:
  format-check:
    name: Format check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache Node.js dependencies
        id: cache-node
        uses: actions/cache@v4
        with:
          path: e2e/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: make e2e-setup-ci

      - name: Check formatting
        run: make e2e-format-check-native
