name: CI Infra Service Checks

on:
  # !! Uncomment to trigger automated infra tests once dev environment is set up
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - infra/*/service/**
  #     - infra/modules/**
  #     - infra/test/**
  #     - .github/workflows/ci-infra-service.yml
  # pull_request:
  #   paths:
  #     - infra/*/service/**
  #     - infra/modules/**
  #     - infra/test/**
  #     - .github/workflows/ci-infra-service.yml
  workflow_dispatch:

jobs:
  infra-test-e2e:
    name: Test service
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.19.0"

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: app
          # Run infra CI on dev environment
          environment: dev

      - name: Run Terratest
        run: make infra-test-service
