name: CI Infrastructure Checks

on:
  push:
    branches:
      - main
    paths:
      - infra/**
      - .github/workflows/ci-infra.yml
  pull_request:
    paths:
      - infra/**
      - .github/workflows/ci-infra.yml

jobs:
  check-terraform-format:
    name: Check Terraform format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.1
          terraform_wrapper: false

      - name: Run lint-infra
        run: |
          echo "If this fails, run 'make format-infra'"
          make lint-infra
