name: NextJS CI

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    name: pass/fail checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install --location=global yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn lint
    - run: yarn format-check
    - run: yarn test
    