name: Database migrations

on:
  workflow_call:
    inputs:
      app_name:
        description: "name of application folder under infra directory"
        default: app
        type: string
      environment:
        description: "the name of the application environment (e.g. dev, staging, prod)"
        required: true
        type: string

concurrency: database-migrations-${{ inputs.environment }}

jobs:
  build-and-publish:
    name: Build
    uses: ./.github/workflows/build-and-publish.yml
    with:
      ref: ${{ github.ref }}
  run-migrations:
    name: Run migrations
    runs-on: ubuntu-latest
    needs: [build-and-publish]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # !! Update the role-to-assume with the GitHub actions role ARN
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<PROJECT_NAME>-github-actions
          aws-region: us-east-1
      - name: Run migrations
        run: make release-run-database-migrations APP_NAME=${{ inputs.app_name }} ENVIRONMENT=${{ inputs.environment }}
