name: Database migrations

on:
  workflow_call:
    inputs:
      app_name:
        description: "name of application folder under infra directory"
        required: true
        type: string
      environment:
        description: "the name of the application environment (e.g. dev, staging, prod)"
        required: true
        type: string
      version:
        description: "git reference to deploy (e.g., a branch, tag, or commit SHA)"
        required: true
        type: string
    outputs:
      commit_hash:
        description: The SHA that was used for migrations
        value: ${{ jobs.build-and-publish.outputs.commit_hash }}

concurrency: database-migrations-${{ inputs.app_name }}-${{ inputs.environment }}

jobs:
  build-and-publish:
    name: Build
    uses: ./.github/workflows/build-and-publish.yml
    with:
      app_name: ${{ inputs.app_name }}
      ref: ${{ inputs.version }}
  run-migrations:
    name: Run migrations
    runs-on: ubuntu-latest
    needs: [build-and-publish]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: ${{ inputs.app_name }}
          environment: ${{ inputs.environment }}

      - name: Run migrations
        run: |
          make release-run-database-migrations APP_NAME=${{ inputs.app_name }} ENVIRONMENT=${{ inputs.environment }} IMAGE_TAG=${{ needs.build-and-publish.outputs.commit_hash }}
