name: Deploy

on:
  workflow_call:
    inputs:
      app_name:
        description: "name of application folder under infra directory"
        required: true
        type: string
      environment:
        description: "the name of the application environment (e.g. dev, staging, prod)"
        required: true
        type: string
      version:
        description: "git reference to deploy (e.g., a branch, tag, or commit SHA)"
        required: true
        type: string
    outputs:
      commit_hash:
        description: The SHA that was deployed
        value: ${{ jobs.database-migrations.outputs.commit_hash }}

concurrency: cd-${{inputs.app_name}}-${{ inputs.environment }}

jobs:
  # Don't need to call the build-and-publish workflow since the database-migrations
  # workflow already calls it
  database-migrations:
    name: Database migrations
    uses: ./.github/workflows/database-migrations.yml
    with:
      app_name: ${{ inputs.app_name }}
      environment: ${{ inputs.environment }}
      version: ${{ inputs.version }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [database-migrations]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: ${{ inputs.app_name }}
          environment: ${{ inputs.environment }}

      - name: Deploy release
        run: make release-deploy APP_NAME=${{ inputs.app_name }} ENVIRONMENT=${{ inputs.environment }} IMAGE_TAG=${{ needs.database-migrations.outputs.commit_hash }}
