name: NextJS Deploy

on:
  workflow_call:
    secrets:
      ACCOUNT_ID:
        required: true

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    name: Deploy NextJS Application
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app                        ................ this is a pain in the ass

    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{secret.ACCOUNT_ID}}:role/github-actions-assume-role
        role-duration-seconds: 900                                                
        role-session-name: githubactions
        aws-region: us-east-1

    - name: Verify we have authenticated
      run: |
        aws sts get-caller-identity

# We are gonna need some switches for environments
# on:
#   push:
#     branches:
#       - main
#     paths:          # might be good to add to fine tune control...        
#       - app/**    
#   pull_request:
#     paths:
#       - admin/**

# build:
# # build the image
# deploy-ecr:
  # runs-on: ubuntu-latest
  # needs: build
  # if: "what??"
  # environment: ${{ secrets.ENV }}
# deploy-ecs:
  # runs-on: ubuntu-latest
  # needs: deploy-ecr
  # if: "what??"
  # environment: ${{ secrets.ENV }}
  # steps:
  # - name: 
  # - use: actions/checkout@v3
  