name: PR Environment Destroy
run-name: Destroy PR Environment ${{ github.event.number }}
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  destroy:
    name: Destroy environment
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write # Needed to comment on PR

    concurrency: pr-environment-${{ github.event.number }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: ${{ inputs.app_name }}
          environment: ${{ inputs.environment }}

      - name: Destroy environment
        run: ./bin/destroy-pr-environment "${{ inputs.app_name }}" "${{ inputs.environment }}" "${{ github.event.number }}"
        env:
          GH_TOKEN: ${{ github.token }}
