name: Template CI Infra Checks

on:
  push:
    branches:
      - main
      - lorenyu/templateonlyci
  pull_request:
    paths:
      - template-only-infra/**
      - infra/modules/**
      - .github/workflows/template-only-ci-infra.yml

# For now, only allow workflow run at a time, since this actually provisions infra.
concurrency: platform-template-only-ci-infra

jobs:
  test:
    name: Infra Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.1
          terraform_wrapper: false
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::368823044688:role/platform-template-infra-github-actions
      - name: Run Terratest
        run: make -f template-only.mak test
