name: Template CI Test PRs
run-name: ${{ github.workflow }} - ${{ inputs.action || github.event.pull_request.state }}

on:
  workflow_dispatch:
    inputs:
      src_branch_name:
        required: true
        type: string
      dest_branch_name:
        type: string
      action:
        type: choice
        options:
          - update
          - close
        default: update
  # TODO: enable when ready
  # pull_request:
  #   paths:
  #     - "**"
  #     - "copier.yml"
  pull_request_target:
    types: [closed]

# all access is via `PLATFORM_BOT_GITHUB_TOKEN`
permissions: {}

jobs:
  get-params:
    name: Get parameters with some processing
    runs-on: ubuntu-latest
    outputs:
      src_branch_name: ${{ steps.get-params-step.outputs.src_branch_name }}
      dest_branch_name: ${{ steps.get-params-step.outputs.dest_branch_name }}
    steps:
      - name: get
        id: get-params-step
        env:
          GITHUB_HEAD_REF: github.head_ref
        run: |
          src_branch_name="${{ inputs.src_branch_name || env.GITHUB_HEAD_REF }}"

          echo "src_branch_name=${src_branch_name}"
          echo "src_branch_name=${src_branch_name}" >> "$GITHUB_OUTPUT"

          if [[ -n "${{ inputs.dest_branch_name  }}" ]]; then
            dest_branch_name="${{ inputs.dest_branch_name }}"
          else
            dest_branch_name="test-pr|${{ github.repository }}|${src_branch_name}"
          fi

          echo "dest_branch_name=${dest_branch_name}"
          echo "dest_branch_name=${dest_branch_name}" >> "$GITHUB_OUTPUT"

  update:
    name: " " # GitHub UI is noisy when calling reusable workflows, so use whitespace for name to reduce noise
    uses: ./.github/workflows/template-only-create-or-update-test-pr.yml
    if: (github.event_name == 'workflow_dispatch' && inputs.action == 'update') || github.event.pull_request.state == 'open'
    needs: get-params
    with:
      src_branch_name: ${{ needs.get-params.outputs.src_branch_name }}
      dest_branch_name: ${{ needs.get-params.outputs.dest_branch_name }}
      project_repo: navapbc/platform-test
    secrets:
      access_token: ${{ secrets.PLATFORM_BOT_GITHUB_TOKEN }}

  close:
    if: (github.event_name == 'workflow_dispatch' && inputs.action == 'close') || github.event.pull_request.state == 'closed'
    runs-on: ubuntu-latest
    needs: get-params
    steps:
      - name: Close test PR
        env:
          GITHUB_TOKEN: ${{ secrets.PLATFORM_BOT_GITHUB_TOKEN }}
          DEST_BRANCH_NAME: ${{ needs.get-params.outputs.dest_branch_name }}
        run: |
          PR_STATE=$(gh pr list --head "${DEST_BRANCH_NAME}" --repo navapbc/platform-test --json state --jq '.[].state')
          echo "PR_STATE=${PR_STATE}"

          if [[ "${PR_STATE}" == "OPEN" ]]; then
            gh pr close "${DEST_BRANCH_NAME}" --delete-branch --repo navapbc/platform-test
          else
            echo "PR does not exist (or is already closed). Nothing to close."
          fi
