name: Deploy Template

on:
  workflow_dispatch:
    inputs:
      target_repo:
        required: true
        type: string
        description: The GitHub repository of the project to deploy the template to (e.g. "navapbc/platform-test")
  workflow_call:
    inputs:
      target_repo:
        required: true
        type: string
        description: The GitHub repository of the project to deploy the template to (e.g. "navapbc/platform-test")

# Only allow one workflow at a time per repo to prevent race conditions when pushing changes to the project repo
concurrency: cd-${{ inputs.target_repo }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template-infra repo
        uses: actions/checkout@v3
        with:
          path: template-infra
          ref: lorenyu/cdnextjs
      - name: Checkout project repo
        uses: actions/checkout@v3
        with:
          path: project-repo
          repository: $${{ inputs.target_repo }}
          token: ${{ secrets.PLATFORM_BOT_GITHUB_TOKEN }}

      - name: Update infra template
        working-directory: project-repo
        run: ../template-infra/template-only-bin/update-template.sh

      - name: Push changes to project repo
        working-directory: project-repo
        run: |
          git config user.name nava-platform-bot
          git config user.email platform-admins@navapbc.com
          git add --all
          # Commit changes (if no changes then no-op)
          git diff-index --quiet HEAD || git commit -m "Template infra deploy #${{ github.run_id }}"
          git push
