name: Template CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-test:
    name: Deploy to platform-test
    uses: ./.github/workflows/template-only-deploy.yml
    with:
      target_repo: navapbc/platform-test
  deploy-nextjs:
    name: Deploy to platform-test-nextjs
    uses: ./.github/workflows/template-only-deploy.yml
    with:
      target_repo: navapbc/platform-test-nextjs
