name: Template Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      project_repository:
        description: Project repository to deploy to
        default: navapbc/platform-test
        required: true
  # TODO: uncomment before merging this is for testing
  pull_request:

jobs:
  deploy:
    name: Deploy template infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.project_repository }}
          token: ${{ secrets.PLATFORM_BOT_GITHUB_TOKEN }}
      - name: Checkout template-infra repo
        uses: actions/checkout@v3
        with:
          path: template-infra
      - name: Reinstall infra template and cleanup
        # TODO: first add install-template.sh to main branch in a separate PR
        run: |
          cp -r \
            template-infra/.github \
            template-infra/bin \
            template-infra/docs \
            template-infra/infra \
            template-infra/Makefile \
            .
          rm .github/workflows/template-only-*
      - name: Push changes to project repo
        run: |
          git add .
          git commit -m "Template infra deploy #${{ github.run_id }}"
          git push
